version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo_sorter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_sorter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_sorter_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/todo_sorter
      PORT: 3000
      STATIC_DIR: /app/web/dist
      JWT_SECRET: development_secret_key
      JWT_EXPIRY: 86400
    ports:
      - "3000:3000"

volumes:
  postgres_data: 