[phases.setup]
nixPkgs = ["gcc", "binutils", "openssl", "pkg-config", "nodejs-18_x", "yarn"]

[phases.build]
cmds = [
  "cd web && yarn install && yarn build",
  "mkdir -p /app/static",
  "cp -r web/dist/* /app/static/ || true",
  "SQLX_OFFLINE=true RUSTC_VERSION=1.82.0 cargo build --release",
  "chmod +x start.sh"
]

[start]
cmd = "./start.sh" 