[build]
builder = "nixpacks"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
autostart = true

# Railway automatically injects DATABASE_URL environment variable
# when you provision a PostgreSQL database

[services.web]
healthcheck = "/api/health"
port = 3000

# Environment variables
[variables]
PORT = "3000"
STATIC_DIR = "/app/static"
SQLX_OFFLINE = "true"
