[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "on_failure"
startCommand = "/app/target/release/sorter api"

# Environment variables
[variables]
PORT = "3000"
STATIC_DIR = "/app/web/dist"
